### ISSUE TITLE
Several potential memory leaks in jerasure.c

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#11]
According to Clang Static Analyser report there are several potential memory leaks in `jerasure.c` file:
- line 263 - `jerasure_matrix_to_bitmatrix` function - potential leak of memory pointed to by `bitmatrix`
- line 828 - `jerasure_generate_decoding_schedule` function - potential leak of memory pointed to by `row_ids` and `ind_to_row`

**Comment by leobago** [comment]
I think we can fix this issue quickly but I am thinking about transition to Jerasure2 as you proposed in issue #22. However, I am not sure how easy is the transition to Jerasure2, if the API changed too much then that might take longer (we don't want to mess with the erasure codes). So let's fix it manually for now.
