### ISSUE TITLE
Error: Ambiguous interfaces in generic interface 'fit_protect'

### ISSUE THREAD

**Issue by gonsie** [leobago/fti#116]
When compiling FTI, I get the following error:

```fortran
[ 50%] Building Fortran object CMakeFiles/fti_f90.static.dir/interface.F90.o
/.../FTI/build/interface.F90:3004:32:

   subroutine FTI_Protect_REAL161(id_F, data, err)
                                1
/.../FTI/build/interface.F90:3039:32:

   subroutine FTI_Protect_REAL163(id_F, data, err)
                                2
Error: Ambiguous interfaces in generic interface 'fti_protect' for 'fti_protect_real161' at (1) and 'fti_protect_real163' at (2)
make[2]: *** [CMakeFiles/fti_f90.static.dir/interface.F90.o] Error 1
```

**Comment by ksiero** [comment]
Could you tell us what compilers are you using?
Could you send us implementation of this subroutines which is in /.../FTI/build/interface.F90?
This means the subroutines which were generated have exactly the same types. We did not experienced this error before.

**Comment by ksiero** [comment]
If you don't need Fortran interface you can disable it by changing in CMakeList.txt line:
`option(ENABLE_FORTRAN "Enables the generation of the Fortran wrapper for FTI" ON)`
to:
`option(ENABLE_FORTRAN "Enables the generation of the Fortran wrapper for FTI" OFF)`
and call cmake command again

**Comment by gonsie** [comment]
I am using gfortran: GNU Fortran (Homebrew GCC 7.1.0) 7.1.0.

The subroutines are:

```fortran
  subroutine FTI_Protect_REAL161(id_F, data, err)

    integer, intent(IN) :: id_F
    REAL(KIND=16), pointer :: data(:,:,:)
    integer, intent(OUT) :: err

    ! workaround, we take the address of the first array element and hope for
    ! the best since not much better can be done
    call FTI_Protect_Ptr(id_F, &
            c_loc(data(lbound(data, 1),&
lbound(data, 2),&
lbound(data, 1))), &
            size(data), FTI_REAL16, err)

  endsubroutine FTI_Protect_REAL161
```
```fortran
  subroutine FTI_Protect_REAL163(id_F, data, err)

    integer, intent(IN) :: id_F
    REAL(KIND=16), pointer :: data(:,:,:)
    integer, intent(OUT) :: err

    ! workaround, we take the address of the first array element and hope for
    ! the best since not much better can be done
    call FTI_Protect_Ptr(id_F, &
            c_loc(data(lbound(data, 1),&
lbound(data, 2),&
lbound(data, 3))), &
            size(data), FTI_REAL16, err)

  endsubroutine FTI_Protect_REAL163
```

**Comment by kellekai** [comment]
The compiler complains are justified. The ambiguity is located in the line

`REAL(KIND=16), pointer :: data(:,:,:)` 

This should be only in case `FTI_Protect_REAL163`. For the case `FTI_Protect_REAL161` it must be

`REAL(KIND=16), pointer :: data(:)` 

It seems to be a parsing problem during the interface generation.

Which bash version do you have installed (sh --version) ?

**Comment by gonsie** [comment]
`sh --version`

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by leobago** [comment]
We have not been able to reproduce this error in any machine, it seems to be specific to Mac computers. There has been several releases since the bug was reported. We will re-open if the bug is observed again.

**Comment by imamalva** [comment]
i also have the same issue with mac. using this version 
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.

Any solutions ?
