### ISSUE TITLE
Large files in repository

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#119]
There are some files in the repository which are large and not needed anymore. That leads to an unnecessary big size of the repository. There is a stackoverflow post how to find large files in the repository 

-> https://stackoverflow.com/questions/298314/find-files-in-git-repo-over-x-megabytes-that-dont-exist-in-head

the ruby script returns:

55.9M    MLNX_OFED/DEBS/mft-4.6.0-51.amd64.deb    (855b0a2: 3 months ago)
 9.9M    MLNX_OFED/DEBS/mlnx-fw-updater_4.0-2.0.0.0_amd64.deb    (855b0a2: 3 months ago)
10.0M    MLNX_OFED/DEBS/openmpi_2.0.2a1-0.40200_all.deb    (855b0a2: 3 months ago)
57.1M    MLNX_OFED/src/MLNX_OFED_SRC-4.0-2.0.0.1.tgz    (855b0a2: 3 months ago)

there is a procedure to clean the branch from this files here 

-> https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

**Comment by kellekai** [comment]
**First approach**
After identifying the files, we may delete them by cloning the master branch of the repository changing into it and applying:
`git filter-branch --tree-filter 'rm -rf MLNX_OFE*' HEAD`
This approach is taken from:
https://stackoverflow.com/questions/8083282/how-do-i-remove-a-big-file-wrongly-committed-in-git

Details on the command `git filter-branch` are here:
https://git-scm.com/docs/git-filter-branch

**Second approach**
Using the Java program bfg (https://rtyley.github.io/bfg-repo-cleaner/#usage)
https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

In my opinion, the first approach is the most promising.

**Comment by leobago** [comment]
Cleaned. Please everybody ditch your local copies of the FTI repository and make a fresh clone.
