### ISSUE TITLE
Switch to the New BSD License

### ISSUE THREAD

**Issue by leobago** [leobago/fti#158]
Hi, 

we are planing to switch FTI to the new 3-clause BSD License. Please let me know if this is fine with you or if you have an issue. Here is a short summary of it (The full license will be added to the sources):

===========
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 
- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
- Neither the name of the <organization> nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

===========

Thanks!

**Comment by kellekai** [comment]
Thats fine for me!

**Comment by jbigot** [comment]
Perfect for me

**Comment by ksiero** [comment]
Good for me and Tomek

**Comment by nuriallv** [comment]
Good for me.

**Comment by leobago** [comment]
Great! Thank you all.
