### ISSUE TITLE
Move call of FTI_RecoverFiles to FTI_Recover

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#166]
I wonder if we could move calling FTI_RecoverFiles from FTI_Init to FTI_Recover function. This is intuitive to me that we check if we can recover when we want to recover. This move will give me advantage to check if data was corrupted after we load it to the memory. We want to split checkpoints to containers(files), but remain only 1 checksum of checkpoint saved in metadata.

**Comment by ksiero** [comment]
Also this change is good for HDF5 files, because checksum of data and checksum of file is different.

**Comment by leobago** [comment]
The reason for FTI_RecoverFiles to be in the FTI_Init is that it is useless to pass through all the initialization phase of an application if the restart will fail anyway. Therefore, we make sure that the restart is actually possible before doing anything else. On the other hand by the end of FTI_RecoverFiles all files should already be in local storage, so the checksum verification should not invoke any PFS read.
