### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#167]
How much we want to keep backward compatibility?
This are my ideas to make FTI little bit simple for user:
1. Change:
```C
int FTI_Protect(int id, void* ptr, long count, FTIT_type type)
```
to
```C
int FTI_Protect(void* ptr,  long count, FTIT_type types, int containerID) //returns id of variable (-1 if failed)
```
2. Add function:  
```C
int FTI_UpdateVariable(void* ptr,  long count, FTIT_type types)
```
to make clear that user changes variable not protecting new one. Additional advantage is that we won't iterate through all variables, because index in FTI_Data is the variable ID.

3. Change:
```C
int FTI_Checkpoint(int id, int level)
```
to
```C
int FTI_Checkpoint(int level) //returns id of checkpoint (-1 if failed)
```
4. Add function: 
```C
int FTI_RecoverContainer(int containerID)
```

If we want to keep backward compatibility at all cost we could make functions wrappers, e.g.:
```C
int FTI_Protect(int id, void* ptr, long count, FTIT_type type) {
    //Search for dataset with given id to know if update or create
    int i;
    for (i = 0; i < FTI_Exec.nbVar; i++) {
        if (id == FTI_Data[i].id) {
            return FTI_UpdateVariable(id, ptr, count, type);
        }
    }
    return FTI_ProtectNew(id, ptr, count, type, 0);
}
```
To make ids the same way we could use mapping, e.g.:
```C
int varIDMap[FTI_BUFS];
...
int IDSetByUser = varIDMap[id]; //id automatically incremented
```

**Comment by leobago** [comment]
Most of the relevant changes for the API have been implemented in different features and releases.
