### ISSUE TITLE
Alignment of checkpoint data in files to allow differential/incremental checkpointing 

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#168]
Requirements
===

*(i)* Datafields may be added at any point
*(ii)* Datafields may change size at any point
*(iii)* Allowance of incremental/differential checkpointing

From *(iii)* follows that the position of datafileds in the file must not change.

Scenario
---

1) Protect p variables
2) Perform checkpoint
3) Add q protected variables
4) Perform checkpoint
5) Expand size of i variables 
6) Shrink size of j variables  

Datastructure
---

|`data-hash`|`DB-struct`|`VAR-struct[]`|`DATA[1]`|{`META[2]`|`DATA[2]`|,...,|`DATA[k]`|`META[k]`|}

|`data-hash`| := hash of whole data in checkpoint file (for consistency check on restart)

|`DB-struct`|`VAR-struct[]`| := `META[1]`

The file structure is then:

|`data-hash`|`META[1]`|`DATA[1]`|,...,|`META[k]`|`DATA[k]`|

The structs are defined as:

```C
DB-struct {
    flag // 0 if last datablock, 1 else
    numVars // number of variables in datablock
}

VAR-struct {
    id // variable ID
    size // datafield size in Bytes
    flag // 0 if last occurence in file, 1 else
    DB-next // if flag == 1, index of datablock of next occurence
}
```

Notes
---
   
- On a restart, first we read all the metadata blocks.

**Comment by ksiero** [comment]
This looks like new file format :)
I think we could just use checksums join with HDF5 which is optimized and gives all advantages we need.

**Comment by kellekai** [comment]
true ;) but we would also add another software dependency...

**Comment by ksiero** [comment]
We could use HDF5 as optional feature like we using SIONlib :)

**Comment by leobago** [comment]
That sounds like an interesting idea, what would be the requirements and constrains of matching the HDF5 format?

**Comment by ksiero** [comment]
I don't know much about HDF5, but it creates file which contains groups and datasets (group can include group) which gives something like paths to get to datasets. Good thing about HDF5 is that practically everything can have metadata, so we won't need creating separate files for metadata. HDF5 is flexible (can append data to the datasets) also if size of array doesn't change it can fast override the data in file

**Comment by leobago** [comment]
Sounds nice. What extra information would need to be given in the protect call to match HDF5 format?

**Comment by ksiero** [comment]
I think we need just type and size of datasets

**Comment by leobago** [comment]
We already have that right? So basically our local checkpoint files will be written in HDF5 format, and then moved to partner, RS or PFS depending on the level, right?

**Comment by ksiero** [comment]
In my opinion it should work

**Comment by leobago** [comment]
Good! Can you give it a try?

**Comment by ksiero** [comment]
Sure! :)

**Comment by ksiero** [comment]
HDF group is creating something like HDF Cloud: https://www.hdfgroup.org/hdf-cloud/

I think we count merge our idea with containers in it. I mean each container would be a dataset in HDF5 file and it would be easier to map dataset into S3 buckets. What do you think?

**Comment by kellekai** [comment]
How do we implement the differential ckpt in it? Can we change particular elements in an hdf5 file?

**Comment by ksiero** [comment]
I didn't test it but this is in User's Guide:
"HDF5 datatypes implement a flexible, extensible, and portable mechanism for specifying and discovering the storage layout of the data elements, determining how to interpret the elements (e.g., as floating point numbers), and for transferring data from different compatible layouts."
