### ISSUE TITLE
coding style

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#170]
We need to agree on the tabwidth in the files.

In some files it is 3 spaces in others it is 4.

What about having 1 tab = 4 spaces (most common) always?

**Comment by ksiero** [comment]
Me and Tomek have 4 spaces.
What about new line sign? I think:
- conf.c
- meta.c
- postckpt.c
- topo.c
still have CRLF.

**Comment by leobago** [comment]
Fixed.
