### ISSUE TITLE
additional unitary tests

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#179]
> **In general all tests where possible and meaningful have to be performed for the head=1 case as
> well and it should be for at least 32 ranks (better 64 ranks if possible), group size of 4 and 4
> processes per node. Also a memory size of at least about 20 MB per process is desireable.**

## 1) MPI-IO, HDF5, FTI-FF and SIONlib 
port all existing unitary tests to the provided IO's ( as far as compatible )

### 2.1) Consistency of the ckpt-files after successful recovery 
After the restart from any level, we claim to have the same state as after the successful checkpoint
in the preceeding execution. We need to proof this in a unitary test. For instance:

> 1. init fti
> 2. perform checkpoint
> 3. simulate crash
> 4. delete all partner/encoded files
> 5. restart
> 6. after successful restart, simulate crash again
> 7. delete all checkpoint files
> 8. restart and check if restart successful

### 2.2) Assure the consistency of checkpoint files for keep\_last\_ckpt is true
Same as before. After the successful restart, we claim to have the situation as after the last
checkpoint in the preceeding execution.

> 1. init fti
> 2. perform checkpoint
> 3. finalize
> 5. restart
> 6. after successful restart, simulate crash
> 8. restart and check if restart successful

#### 2.3.1)
combine two different problems in one code. Init the first and finalize at the end. then (within
same source and execution) init fti again and perform the execution of the second problem and
finalize at the end. Check for warnings or errors.

#### 2.3.2) 
check for a correct restart without the crash of the application.

> **for all levels:**
> 1. init fti
> 2. perform checkpoint
> 3. init fti
> 4. finalize

> **for all levels: (keep\_last\_ckpt=1)**
> 1. init fti
> 2. perform checkpoint
> 3. finalize
> 4. init fti

## 3) FTI functions
We need to check if the functions in FTI behave as wanted for every possible case. For instance, if
within FTI\_Checkpoint the checkpoint is not performed correctly, we need to discard the checkpoint
and FTI has to be on the state as from before the attempt.

This is only one example. We need to do this kind of checks for all internal and API functions
within FTI. The whole scope of these tests has to be investigated. 

### 3.1) 
Perform the above for all the API functions

### 3.2) 
Perform the above for all the internal functions

#### 4.1.1)
If we have performed a successful checkpoint, the older checkpoint from before is kept if the
security (level) was higher then the current. In the other case, if the security was lower, the
checkpoint will be removed.

#### 4.1.2)
Also, for keep\_last\_ckpt=1, beside the flushed L4 checkpoint on the parallel file system, the
local checkpoint files (for the case of L1, L2, L3) aren't kept.

We need a unitary test which proofs these features.
### 4.2) Recover-hierarchy
This is related to 4.1. On a restart, FTI will restart from the lowest level. Hence if we have both,
L1 and L4, FTI should restart from L1. If it fails, it should restart from L4 (see 4.1.2).

This is to proof.

**Comment by kellekai** [comment]
I would set the priority to: 1) -> 3.1) -> 4) -> 2) -> 3.2)

**Comment by ksiero** [comment]
Points 2) and 3) done and integrated with Travis in #184
Point 1) done in #185
