### ISSUE TITLE
Resource leaks in FTI_RecoverL2 function

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#18]
According to cppcheck there are potential resource leaks in `postreco.c` file caused by not closing file associated with `jfd` stream (line 156) or file associated with `lfd` stream (line 157) or file associated with `pfd` stream (line 170) or file associated with `qfd` stream (line 193).

**Comment by leobago** [comment]
We might have to write a "cleanup" function that would close every open file and free every allocated buffer to avoid code repetition. In the mean time, this fix seems fine.
