### ISSUE TITLE
Remaining FTI test

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#186]
## 3) FTI functions
We need to check if the functions in FTI behave as wanted for every possible case. For instance, if
within FTI\_Checkpoint the checkpoint is not performed correctly, we need to discard the checkpoint
and FTI has to be on the state as from before the attempt.

This is only one example. We need to do this kind of checks for all internal and API functions
within FTI. The whole scope of these tests has to be investigated. 

### 3.1) 
Perform the above for all the API functions

### 3.2) 
Perform the above for all the internal functions

**Comment by leobago** [comment]
A complete rebrand of the tests has been done. For more details please check https://fault-tolerance-interface.readthedocs.io/en/latest/itf.html
