### ISSUE TITLE
Missing/incorrect pattern files for Travis unitary tests

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#189]
For FTI-FF there are insufficient pattern files and some of the existing do not apply correctly to the results.

**Comment by kellekai** [comment]
this is also the case for hdf5... Missing pattern files are: L10, L20, L30, L40, L202

**Comment by kellekai** [comment]
Changed milestone. The pattern for hdf5 are not included because we not yet test the checkpoint file on consistency in this format.

**Comment by leobago** [comment]
ITF added.
