### ISSUE TITLE
Use of version 2.0 of the jerasure library

### ISSUE THREAD

**Issue by ghost** [leobago/fti#22]
There is newer version of the jerasue library http://jerasure.org

As written on the homepage 

> This is pretty much Jerasure 1.2 without the original Galois Field backend. Version 2.0 links directly to GF-Complete, which is more flexible than the original, and _much_ faster, because it leverages SIMD instructions.

It should be useful to replace the current library version with the newer one, especially from the performance point of view.

**Comment by leobago** [comment]
Agreed. I think the only places where we use the Jerasure library is in postckpt and postreco. Let's see if the API offered is the same, and if it is let's switch to Jerasure2. I will not assign a milestone yet, as this is not urgent.

**Comment by kellekai** [comment]
With pull request #128 the migration to Jerasure2.0 is accomplished.
