### ISSUE TITLE
FTI build bug

### ISSUE THREAD

**Issue by tomaszpal** [leobago/fti#224]
When building `FTI release 1.2`  without `openssl` there is an undefined function used in `src/diff-checkpoint.c`:   
```shell
.../fti/src/FTI/src/ftiff.c:1031:17: warning: implicit declaration of function ‘MD5’ [-Wimplicit-function-declaration]
                 MD5( (FTI_ADDRPTR) cbasePtr, currentdbvar->chunksize, hashchk );


.../fti/src/FTI/src/diff-checkpoint.c:514:17: warning: implicit declaration of function ‘MD5’ [-Wimplicit-function-declaration]
                 MD5( ptr, hashInfo->blockSize, md5hashNow);

    ...

.../fti/src/FTI-build/lib/libfti.so: undefined reference to `MD5'
```
Based on `deps/md5/md5.h`:
```c
#ifdef HAVE_OPENSSL
#include <openssl/md5.h>
#elif !defined(_MD5_H)
    ...
#endif
```
 I assume that `FTI` should be able to build without `openssl` and in that case should use provided header and implementation in `deps/md5`, but the `MD5` function in `deps/md5/md5.h`  is (probably) missing.  
Building with `openssl` works fine.

**Comment by koparasy** [comment]
This bug has been fixed.
