### ISSUE TITLE
FTI_RecoverVar bug?

### ISSUE THREAD

**Issue by tomaszpal** [leobago/fti#228]
`FTI_RecoverVar` sometimes requires to protect all variables to recover a variable and sometimes doesn't.  
I think it's because implementation assumes the same order of protecting variables.  
In file `api.c line: 2213` :
```
for (i = 0; i < FTI_Exec.nbVar; i++) 
{ 
if (id == FTI_Exec.meta[FTI_Exec.ckptLvel].varID[i])
...
}
```
Code above doesn't check if the variable `id` was protected after some other variables.

**Comment by koparasy** [comment]
This bug should be fixed in the last push
