### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#24]
I've some remarks regarding the code structure. To increase readability and maintainability we should consider:
- use of some coding style - this can be done automatic and in-place using ClangFormat tool http://clang.llvm.org/docs/ClangFormat.html
- splitting of the source code into functionally independent subprojects (config parser, jerasure, fti) and alternatively later use of cmake ExternalProject module (view issue #23)
- unifying the build system for library code and examples

**Comment by leobago** [comment]
This is a great idea, I wanted to do this for long time but I never took the time. Let's reformat the code with the ClangFormat tool and let's unify the build of library code and examples.

**Comment by leobago** [comment]
I guess this has been done, right?
