### ISSUE TITLE
Use of external services for automatic code compilation and testing

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#25]
There are several external services which are free for open source projects, can be used for automatic code compilation, building, checking, etc. and are easy to integrate with github based projects.

Continous Integrations
- travis https://travis-ci.org
- appveyor https://ci.appveyor.com

Static analysis
- coverity scan https://scan.coverity.com

Code coverage
- coveralls https://coveralls.io

**Comment by leobago** [comment]
Thank you for the ideas. I just took a look at them and they look nice. Let us discus these options in the next conf-call.

**Comment by leobago** [comment]
I guess this is already covered, right?
