### ISSUE TITLE
Fortran interface to FTI with HDF5 IO

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#302]
When using FTI in combination with the HDF5 IO in FORTRAN applications, the data types in the HDF5 checkpoint file are incorrect for real valued variables.

For instance, when protecting a real(8) variable in FORTRAN, The data type in the HDF5 file is a 64-bit integer. This is problematic when post-processing the checkpoint files with python or other HDF5 bindings.

**Comment by alexandrelimassantana** [comment]
Fixed in #340
