### ISSUE TITLE
FTI 1.4 has 1.3 version defined in CMakeLists.txt

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#323]
```cmake
include(CMakePackageConfigHelpers)
set(INSTALL_CMAKEDIR "${CMAKE_INSTALL_DATADIR}/FTI/cmake" CACHE PATH "cmake modules directory (DATADIR/FTI/cmake)")
write_basic_package_version_file("${CMAKE_BINARY_DIR}/FTIConfigVersion.cmake"
		VERSION "1.3"
		COMPATIBILITY AnyNewerVersion
)
```

The `https://github.com/leobago/fti/archive/1.4.tar.gz` FTI release has still 1.3 version defined in cmake

**Comment by alexandrelimassantana** [comment]
Thanks for letting us know of this @ksiero, a patch is in the pipeline :)

**Comment by leobago** [comment]
The patch has been merged in the develop branch. We will soon merge it into the master branch together with other fixes.
