### ISSUE TITLE
Main branch of the FTI

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#335]
Already ask that question on #286, but with no response.

I can see that some fixes are made on `master` branch, and some on `develop` branch.
Which one should be used?
Will be there any update to `1.4` release? Maybe `1.4.1` to have a release with fixed bugs?

**Comment by leobago** [comment]
Hi @ksiero, sorry for the delay in our answer, but we wanted to fix all those issues before making the new tag. Now all raised issues have been fixed and have been integrated into the new tag 1.4.1. Please use that as your baseline. In the future, if you want to keep up-to-date with the latest features of FTI (even before release), we recommend you to use the master branch. The develop branch is unstable, so we do not recommend to use it.

**Comment by ksiero** [comment]
Great, but the cmake fix described in #326 and done in #333 is not in the `1.4.1` release. It is only on this `develop` branch.

**Comment by leobago** [comment]
You are right, we are merging that into master today, and hopefully finish fixing a Fortran/HDF5 bug, then we move to tag 1.4.2. Do you need this urgently?

**Comment by ksiero** [comment]
No, I am already using my branch with this fix included

**Comment by leobago** [comment]
It has been merged into master.

**Comment by jbigot** [comment]
As discussed, it would be great if this could be included in a tagged & released version. Can we re-open this issue in the meantime?

**Comment by leobago** [comment]
Ok, we will close it with the next release.

**Comment by jbigot** [comment]
great, thanks :+1:

**Comment by jbigot** [comment]
Any idea on your timeline plans for a release?

**Comment by leobago** [comment]
The plan is this week.

**Comment by jbigot** [comment]
Great news, thanks :+1:

**Comment by leobago** [comment]
Hello, release 1.5 is out.

**Comment by jbigot** [comment]
One day, two great news, thanks!
