### ISSUE TITLE
Datatype management in FTI creates redundant objects

### ISSUE THREAD

**Issue by alexandrelimassantana** [leobago/fti#343]
The **FTI_InitType()** registers primitives, user-defined, and return this information to users as **FTIT_Type** objects.
The function creates a copy of the object to keep in FTI's internal state structures.
When protecting a variable, the user must provide an **FTIT_Type** object to the function.
However, **FTI_Protect()** uses both the internal copy and the user-provided object.

These redundant objects are not guaranteed to be synchronized.
If the user modifies one of its object's attributes, there is no guarantee that FTI will see these changes.

HDF5 has the same method for creating types in their public API.
Users see datatypes as identifiers (i.e h_id) instead of their internal representation.
FTI can benefit of such format as this would limit creating object copies for fear of the user de-allocating these resources.
As it is with HDF5, this might create the need to "close" (i.e deallocate) datatypes.

**Comment by alexandrelimassantana** [comment]
A possible solution to this problem is presented throughout commits in PR #346.

**Comment by leobago** [comment]
Solution provided in PR #346 has been merged.
