### ISSUE TITLE
Compilation bug when building FTI with Fortran support

### ISSUE THREAD

**Issue by alexandrelimassantana** [leobago/fti#344]
When building FTI with the flag '--enable-fortran' an additional build folder is created by CMake.
This can be tested with the **install.sh** bash script in the root folder.
The additional folder will be created under the name **'build'$'\n''      '**.
This might indicate some bug within the compilation steps when Fortran support is enabled.

**Comment by alexandrelimassantana** [comment]
The solution is presented in PR #346 last commit.

**Comment by leobago** [comment]
Bug fixed in PR #346 and merged into master.
