### ISSUE TITLE
Option for no local storage / small jobs

### ISSUE THREAD

**Issue by tjb900** [leobago/fti#35]
Hi,

I've been playing with integrating FTI into a code I have and have realised a little late that I now can't run small test jobs (< 3 nodes), or run on nodes without node-local storage.

It seems possible to write the configuration such that local storage or partner nodes aren't needed, but these configurations are not permitted.

Just wondering if this is on anyone's radar?

Regards,
Tim

**Comment by leobago** [comment]
Hi Tim,

Thank you for your posting. 

Concerning your first point about running FTI in small test jobs, FTI has an option called "Local_test" that you can set to 1 and you can run in one single node. FTI will "emulate" a distributed scenario and behave as if it was a distributed execution on multiple nodes.

Concerning the option to run in systems with no local storage you can set all the checkpoint levels frequency to -1, except for level 4 (File system). Then, you set Inline_L4 option to 1 and then FTI will write directly to the file system directly without staging in any intermediary local storage. You will still need to set a ckpt_dir, which you can set to "/tmp" but it will not be used.

Please let me know if this answer your questions.
Thanks,
Leo
