### ISSUE TITLE
Review copyright notices

### ISSUE THREAD

**Issue by christoph-conrads** [leobago/fti#354]
This is a free software project. Nevertheless, the authors or their employers, respectively, remain copyright holders. FTI will probably never be the subject of a copyright law suit but I suggest to keep your copyright notices reasonably accurate.

```sh
#   Copyright (c) 2017 Leonardo A. Bautista-Gomez
#   All rights reserved
#
#   @file   build.sh
#   @author Alexandre de Limas Santana (alexandre.delimassantana@bsc.es)
#   @date   May, 2020
#
```

**Comment by leobago** [comment]
Free software and copyright are different things. The license is clearly explained in the License file in the source code.
