### ISSUE TITLE
[CMake] Exported configuration incomplete

### ISSUE THREAD

**Issue by christoph-conrads** [leobago/fti#355]
FTI provides a CMake configuration file to simplify its use by other software. The build flags provided are incomplete though.

Consider for example a piece of software using an FTI build with HDF5 enabled. To correctly build the software, it is necessary to set `-DENABLE_HDF5` during compilation. Otherwise the build will not be compatible with the binary interface provided by `libfti.so` / `libfti.a` because the structures in [`fti-intern.h`](https://github.com/leobago/fti/blob/b62d550a4ec5e1c22a15a46d942ce9974a2325b3/include/fti-intern.h) will be missing members. It is also necessary for FTI to provide the path to the HDF5 header files used; there may be multiple sets of HDF5 header files available (think sequential/parallel or on the host / inside Conda).

In general CMake tracks this information automatically unless functions like `include_directories` or `add_definitions` are used. This is exactly what FTI's build setup currently does.

A patch CMake setup for **HDF5 only** can be found in my clone of the FTI repository: [cconrads/fti@05ac0299](https://gitlab.inria.fr/cconrads/fti/-/commit/05ac029973ee68580b6e027a2c9ddb8f1ed2a5c5).

Here is the relevant information from an unpatched FTI build (note the missing HDF5 include directory information):
```cmake
set_target_properties(fti.shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5_hl.so"
)
```
Here is the same segment with a patched setup (note the added definition and HDF5 include directory):
```cmake
set_target_properties(fti.shared PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ENABLE_HDF5"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/hdf5/openmpi;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5_hl.so"
)
```

**Comment by leobago** [comment]
Fixed, thanks.
