### ISSUE TITLE
Support sub-minute checkpoint frequency

### ISSUE THREAD

**Issue by jbigot** [leobago/fti#360]
Tests of FTI have to run at least 1min to lead to a checkpoint. In PDI where we have 600+ tests, these are by far the longest. As a result, the number of FTI tests is limited.

It would be great if there was an option (for tests only maybe) to have checkpoints frequency defined in a sub-minute unit.

**Comment by leobago** [comment]
Hi Julien, we have developed a new feature called "fastForwad". The default value should be always 1. If you set it at 2, the checkpoints will be taken twice as fast. So if you set the checkpoint interval to 1 minute and set fastForward to 2, then checkpoints will be taken every 30 seconds. If fastForward = 3 then every 20 seconds, and so on. The parameter only accepts values between 1 and 10.

**Comment by jbigot** [comment]
I didn't know about this feature, thanks a lot!
