### ISSUE TITLE
Provide FTI Spack package 

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#363]
Spack is an independent package manager for Linux (https://github.com/spack/spack).   
  
An FTI Spack package would simplify the installation of FTI since the dependencies will be automatically installed.

**Comment by jbigot** [comment]
packages are available here: https://github.com/pdidev/spack

**Comment by jbigot** [comment]
BTW, you will also find debian, fedora & ubutu packages for FTI here: https://github.com/pdidev/repo
