### ISSUE TITLE
Compilation Error with GCC 4.9.3

### ISSUE THREAD

**Issue by koparasy** [leobago/fti#384]
Compilation fails when compiling with gcc 4.9.3. I am getting the following error:

src/fortran/ftif.c:91:5 error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   for (const char *p=name; *p; ++p)

**Comment by kellekai** [comment]
fixed since commits ec0fff679b2f3f94824a82f4dc514b0315b3e01f and d28e047b1e4bac4b3a8b9916a9e1b5ca5ef2e565
