### ISSUE TITLE
Default behavior for errors from I/O functions

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#39]
In some places in the code there is implicit assumption that functions like mkdir, rmdir, rename return no error. What should be the default behavior for fti functions if the error occurs? I assume that they should always return `FTI_NSCS` in such situation. But maybe you want to print the error only without changing the behavior of the library? At least for now.

**Comment by leobago** [comment]
I think we should print an error and then return FTI_NSCS. Some parts of the code include several tries. Maybe the long term solution is to write a FTI_Mkdir wrapper that tries a predetermined number of times and return FTI_NSCS in case of failure.
