### ISSUE TITLE
Block size option

### ISSUE THREAD

**Issue by ghost** [leobago/fti#40]
In the config block size is set to 1kB. It is also a comment

> Change something here ONLY if you know what you are doing

The question is why such value? From my experience it would be better if the the value was equal to or greater than the block size of an underlaying filesystem. And maybe the library should check itself the smallest reasonable value for this option?

**Comment by sclaomir** [comment]
I was wrong. In the config this option is set to 1MB. Sorry for that :)
But the second question is still valid.

**Comment by leobago** [comment]
Yes, that could be a nice improvement. I think we can put in the TODO list but it is not urgent.
