### ISSUE TITLE
Removing exit calls from library

### ISSUE THREAD

**Issue by ghost** [leobago/fti#45]
Good practice is that library should never call functions like `exit` or `abort`. Instead of this it should always return error codes. And it should be user responsibility to check whether there were errors and decide if application can run further or not.

**Comment by jbigot** [comment]
The approach I use in PDI & paraconf, inspired by HDF5 for example is to let the user register a function that is called when an error occurs. This function receives the error code & message and can abort, but in case it does not, the error code is returned to the user.

https://gitlab.maisondelasimulation.fr/jbigot/pdi/blob/master/src/status.c

https://gitlab.maisondelasimulation.fr/jbigot/libparaconf/blob/master/src/status.c

**Comment by sclaomir** [comment]
In case of FTI (because it has simple and clean interface) I personally prefer to not extend it. I think that few simple to use functions is big plus of this library. But that's just my opinion :)

**Comment by leobago** [comment]
At this point there are only a few exit and abort calls in the api.c file and I think it is easy to get rid of most of them, in the same way we plan to deal with the failed recovery. The only one that should stay is the one in the `FTI_Finalize`. That one will require another discussion that is not urgent now.

**Comment by leobago** [comment]
Fixed on PR #151 .
