### ISSUE TITLE
Keep last checkpoint if no checkpoint was taken during execution

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#48]
What library response should be default? Now such situation generates error. I think warning will be sufficient.

**Comment by leobago** [comment]
I think we just need top check whether any checkpoint was taken during the execution and if not just print a warning message. @kellekai could you please take care of this?

**Comment by kellekai** [comment]
this would be not necessary but we could add a global warning message. in that case we could write warnings independent of the ranks.

**Comment by leobago** [comment]
Solved.
