### ISSUE TITLE
Validating configuration

### ISSUE THREAD

**Issue by sclaomir** [leobago/fti#49]
Now configuration is always validated against all global and checkpoint level specific requirements. But if we want to take e.g. only L1 and L4 checkpoints the application will not run if it doesn't meet also requirements for L2 and L3. Especially Reed-Solomon requirements are often problematic. In my opinion better way will be to check only really needed conditions.

**Comment by leobago** [comment]
@sclaomir Which requirements do you mean? The only ones i see related to L2 and L3 are the inline requirements. If those are the ones you are talking about please go ahead and fix this. Basically you just need to check that the L2 and L3 checkpoint intervals were not set to a negative value and that head is set to 1.

**Comment by leobago** [comment]
Solved.
