### ISSUE TITLE
nodeFlag section synchronization

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#64]
Configuration: head = 0, inlines = 1. I call FTI_Checkpoint. Every process calls FTI_WriteCkpt and 
FTI_PostCkpt. In PostCkpt only one process goes into nodeFlag section (say P1). Let's consider that this process is slow and did not rename FTI_Conf->lTmpDir to FTI_Ckpt[level].dir yet. Another processes (say P2, P3) in this node goes through remaining FTI_Checkpoint and I call FTI_Checkpoint again. Processes P2 and P3 goes into FTI_WriteCkpt where they create FTI_Conf->lTmpDir folder, but they can't because process P1 didn't renamed it yet and this folder exists (this don't raise error yet). Now process P1 renames folder FTI_Conf->lTmpDir to FTI_Ckpt[level].dir. Processes P2 and P3 call FTI_CreateMetadata where they try to write something to folder FTI_Conf->lTmpDir, but this folder 
is not there anymore, because P1 changed it's name. And that's how we get an error.
When I put MPI_Barrier before creating FTI_Conf->lTmpDir in FTI_WriteCkpt everything seems to work fine. This will have impact on performance, because all checkpoints are separated by barrier. I think better solution is make synchronization after nodeFlag section, because this section makes a lot of problems.

Possible solutions:
- MPI_Barrier(FTI_COMM_WORLD) in every checkpoint - big impact on performance
- We need just to synchronize processes in each node. We could make NODE_COMM and call MPI_Barrier to synchronize this processes.
- We can use Send and Recv to synchronize processes in node (Is this less efficient than MPI_Barrier(NODE_COMM)? )
- More ideas?

**Comment by ksiero** [comment]
I noticed there is MPI_Barrier also on master branch, but before nodeFlag section. We can just move this barrier after this section. This should fix problem with renaming folders. Still I think we can replace this barrier with something lighter.

**Comment by leobago** [comment]
I prefer the NODE_COMM idea. Please try and report.

**Comment by ksiero** [comment]
I've run some tests and that's my conclusion. MPI_Barrier with NODE_COMM (only app processes in node) is actually enough to synchronize the nodeFlag section. Unfortunately it is not enough to synchronize globalFlag section (where only 1 app process goes in). There we need MPI_Barrier(FTI_COMM_WORLD).

So we have 2 options:
1. MPI_Barrier(FTI_COMM_WORLD)
2. MPI_Send when process ends nodeFlag and globalFlag section and MPI_Recv before first access to folders by other processes.
