### ISSUE TITLE
Different sizes of checkpoints

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#65]
When the size of checkpoints is changed during the execution FTI recovers only initial size.

**Comment by ksiero** [comment]
The problem is when we want to recover data. When we change variable
size (say make array bigger) during program running, at begging of
code we call FTI_Protect(id, array, arraySize, type). The problem
is exactly in arraySize, because FTI knows only initial array size, not how big it was on last
checkpoint.

To solve this problem we can write the ID, type and size of variables into checkpoint file.

**Comment by leobago** [comment]
This issue has been fixed by PR #90
