### ISSUE TITLE
examples do not compile with intel

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#68]
use MPI
      1
Fatal Error: File 'mpi.mod' opened at (1) is not a GNU Fortran module file
make[2]: *** [examples/CMakeFiles/hdf.exe.dir/fheatdis.f90.o] Error 1

**Comment by ksiero** [comment]
Did you get this error using "cmake" and "make all"?

**Comment by ksiero** [comment]
I had this same problem on Travis. I think the problem is in cmake itself, because when you have 2 different fortran compilers on machine cmake just takes first which is gfortran. If you get rid of gfortran, cmake will find only ifort. That worked for me :)

**Comment by kellekai** [comment]
I have just encountered the same issue on mn4. the fortran example does not compile. 
`Fatal Error: Cannot read module file ‘mpi.mod’`
It happens with both compilers, Intel and Gnu.
If we change from `USE MPI` to `include 'mpif.h'` it works. It is *encouraged* to deploy `USE MPI` though. This is said here -> http://mpi-forum.org/docs/mpi-3.1/mpi31-report/node411.htm

**Comment by kellekai** [comment]
Pull request #143 fixes this issue.
