### ISSUE TITLE
Asynchronous L1 Checkpoint

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#71]
I thought about additional option for user. If he don't want to be sure when last
checkpoint ended and if it saved successfully, but he wants to make his program run faster.

My idea is to get rid of MPI_Barrier(FTI_COMM_WORLD) in FTI_PostCkpt() and replace it with MPI_Ibcast(). A this point every process has to wait for other processes to make the checkpoint.

I think we could add option that every process makes L1 checkpoints independently and call MPI_Ibcast() with checkpoint ID it made in the message. Every process has some array where it saves how many processes made current checkpoint ID. There will be (world_size)^2 messages, and I don't know if it's faster that MPI_Barrier (but I think it is).

If some process get messages (with checkpoint ID = x) from all other processes it updates metadata file (because it knows all processes made that checkpoint) and call last MPI_Ibcast(). When process gets messages (with checkpoint ID = x) from all processes (including itself) it knows it can delete all checkpoint files which have checkpoint ID < x.

The advantage of this approach is that all processes can do this asynchronously. The disadvantage is we could save more than one checkpoint per process, but if checkpoint size is small this shouldn't be a problem. Of course user won't be sure which checkpoint is done correctly before the last process makes this checkpoint ID successfully (and we don't know when it will happen).

For example we have program where ranks 0 - 255 do more work for first half of iteration and ranks 256 - 511 do more work for second half of iterations. In this situation if we do L1 checkpointing with
MPI_Barrier firstly ranks>255 awaits and after some iterations ranks<256 awaits. This could make computation longer for meaningful time.
Now, if user have an option to use asynchronous checkpointing (without MPI_Barrier) ranks>256 won't wait (just make checkpoint) and go faster to second half of iterations.

**Comment by leobago** [comment]
This scenario could arrive but it has not been raised by any user. Will re-open if necessary.
