### ISSUE TITLE
Warning for wrong type in FTI_Protect

### ISSUE THREAD

**Issue by kellekai** [leobago/fti#75]
It might be nice to implement a warning for the case that the size of the protected variable doesn't match the size of the fti_type chosen in FTI_Protect.

Its not that trivial since the address is transformed into a void pointer in FTI_Protect and all information about the type/size gets lost.

Hence without introducing an extra parameter it d not be possible.

**Comment by leobago** [comment]
There seems to be non standard way of checking how big an allocated block is, so it is hard to cross check if what the user defined corresponds to what is in memory.
