### ISSUE TITLE
L2/L3 recovery when files are missing/corrupted

### ISSUE THREAD

**Issue by ksiero** [leobago/fti#76]
L2:
When processes with groupRank = 0 and groupRank = 1 lost their checkpoint file (Ptner files are intact) FTI can't recover. The reason is that if checkpoint file is missing FTI automatically deletes corresponding Ptner file.

L3:
FTI can't recover properly when:
1. Process with groupRank = 0 don't have checkpoint file (protected variables have wrong values).
2. Any process don't have RS file (deadlock).

**Comment by leobago** [comment]
This has been fixed with the L2fix and L3fix PR.
