### ISSUE TITLE
Examples restart execution from scratch at every run with Makefile

### ISSUE THREAD

**Issue by leobago** [leobago/fti#78]
While doing "make hd" in the examples, the execution always starts from scratch even after a previous execution has run and failed. I think this is because the config.fti file is always copied from the backup, then one has to write the mpirun... line to test the restarts, which is a bit annoying. 
A solution is to not copy the config.fti file before running the example. In addition we can add another target, such as "make hdinit" to reinitialize the run from scratch.

**Comment by ksiero** [comment]
Done. Examples fix #79
